language: cpp
compiler: gcc
sudo: required
install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install -yq build-essential gcc-5.1 g++-5.1 make xorg-dev libgl1-mesa-dev
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5.1 40 --slave /usr/bin/g++ g++ /usr/bin/g++-5.1
  - echo 2 | sudo update-alternatives --config gcc
  - |
    CMAKE_URL="http://www.cmake.org/files/v3.17/cmake-3.17.0-rc1-Linux-x86_64.tar.gz"
    mkdir ${TRAVIS_BUILD_DIR}/cmake-local && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${TRAVIS_BUILD_DIR}/cmake-local
    export PATH=${TRAVIS_BUILD_DIR}/cmake-local/bin:${PATH}
after_install:
  - g++ --version
script:
  - cd RayTracer
  - cmake -G 'Unix Makefiles'
  - make
  - ./rt
