version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
platform: x64
clone_folder: c:\RayTracer
install:
- ps: git submodule update --init --recursive
before_build:
- ps: >-
    md c:\RayTracer\build

    cd c:\RayTracer\build

    cmake -G "Visual Studio 16 2019 Win64" ..
build:
  project: c:\RayTracer\build\RayTracer.sln
  parallel: true
  verbosity: normal
after_build:
- ps: >-
    cd C:\RayTracer\build\Release

    rt.exe --headless