version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
platform: x64
image: Visual Studio 2019
clone_folder: c:\RayTracer
install:
- ps: git submodule update -q --init --recursive
before_build:
- ps: >-
    md RayTracer\build

    cd RayTracer\build

    cmake -G "Visual Studio 16 2019" ..
build:
  project: c:\RayTracer\RayTracer\build\RayTracer.sln
  parallel: true
  verbosity: normal
# OpenGL not supported, so a test run will be omitted for now
#after_build:
#- ps: >-
#    C:\RayTracer\RayTracer\build\Release\rt.exe --headless